### PR TITLE
Fixes mxab/thymeleaf-extras-data-attribute#5: Thymeleaf 3.0 support

### PR DESCRIPTION
**Pull request by dtrunk90**

### CODE REVIEW

**Comment by mxab** [comment]
Wow cool, thank you very much. I will review it later today

**Comment by dtrunk90** [comment]
You're welcome. I removed `DataProcessorTest` cause I thought it's enough to have `DialectTemplateEngineTest`. Maybe you can add and adapt it again.

**Comment by mxab** [comment]
Hi @dtrunk90 I noticed that the missingProperty test fails, which means that
`data:foo="${someMissing}"` results in `data-foo=""` which I actually think is ok, but for some reason I had this test for version 1, any thoughts on this from your side?

**Comment by dtrunk90** [comment]
Hey. Yes, but it's simple to remove the whole attribute if empty. I could update the code tomorrow if you want. Or take a look at this one: https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/standard/processor/AbstractStandardAttributeModifierTagProcessor.java#L100

You just need to check `newAttributeValue` here: https://github.com/dtrunk90/thymeleaf-extras-data-attribute/blob/master/thymeleaf-extras-data-attribute/src/main/java/com/github/mxab/thymeleaf/extras/dataattribute/dialect/DataProcessor.java#L72

`structureHandler.removeAttribute(targetAttrCompleteName);` removes the original `data-`-Attribute whereas `StandardProcessorUtils.replaceAttribute()` replaces `data:attr` with `data-attr`.

Since Thymeleaf 3 there's also a NoOp-Expression: http://www.thymeleaf.org/doc/articles/thymeleaf3migration.html#the-no-operation-token

Here is an example on how to handle those expressions: https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/standard/processor/AbstractStandardExpressionAttributeTagProcessor.java#L91

**Comment by mxab** [comment]
ok, thanks.
One more question about thymeleaf 3, currently the `data:msg="#{my.message}"` tests doesn't work as well.

It looks like thymeleaf evaluates this two times now. Once where it looks up the message "Hello World", but then tries to evaluate the value as well.

I didn't found anything on the thymeleaf3 docs about # so far, any idea?

```
org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as expression: "Hello World" (template: "src/test/resources/test.html" - line 3, col 27)
	at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:131)
	at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:62)
	at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:44)
	at com.github.mxab.thymeleaf.extras.dataattribute.dialect.DataProcessor.processDataAttribute(DataProcessor.java:65)
	at com.github.mxab.thymeleaf.extras.dataattribute.dialect.DataProcessor.process(DataProcessor.java:53)
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1289)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:662)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1086)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1047)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1036)
	at com.github.mxab.thymeleaf.extras.dataattribute.dialect.DialectTemplateEngineTest.test(DialectTemplateEngineTest.java:29)
...
```

**Comment by dtrunk90** [comment]
I'm not really familiar in building a template engine manually for test cases. Now using `thymeleaf-testing` the tests are all working. It's more clearly arranged.

**Comment by dtrunk90** [comment]
Any news here?

**Comment by mxab** [comment]
Hi, sorry for the delay. I had some busy weeks, hopefully in the next view days. I really appreciate your effort.

**Comment by mxab** [comment]
wow i just realised that I had not pulled all your latest changes. these tests look really great

**Comment by mxab** [comment]
@dtrunk90 would you like your name mentioned in the pom file developers section?

**Comment by dtrunk90** [comment]
That would be nice but it's your decision ;-)

**Comment by mxab** [comment]
ok it should be released, thanks again for the work!

**Comment by dtrunk90** [comment]
You're welcome

**Comment by robvanderboom** [comment]
Hi just now see post "One more question about thymeleaf 3, currently the data:msg="#{my.message}" tests doesn't work as well.It looks like thymeleaf evaluates this two times now. Once where it looks up the message "Hello World", but then tries to evaluate the value as well.".

I just posted an issue (https://github.com/mxab/thymeleaf-extras-data-attribute/issues/8) that looks similar.  Is there already a fix for this issue or a workarround issue (i.e. trough a template change..) ?

**Comment by dtrunk90** [comment]
The unit tests are working well. That could be your configuration. Did you followed the [migration guide](http://www.thymeleaf.org/doc/articles/thymeleaf3migration.html)? Check your classpath and Thymeleaf configuration.

**Comment by robvanderboom** [comment]
yes i did follow the migration path.  But an example is always different then a full project. When i make a small new project/example myself (with the same libraries) it is also working.... But together with more functionality like the layout-dialect, all spring functionality, etc. etc it gives this effect. 
The migration guide says if you replace all new libraries (also use the new spring versions) and do the steps in the migration guide it should work... But it does not :-< And don't know where to start.

**Comment by robvanderboom** [comment]
And also the project is to big to change to new ways of writing (like [[ ]] is added for template variables). But the migration guid does not say old ways of syntax like i given above don't work anymore...

**Comment by dtrunk90** [comment]
You don't need to change the templates. You only need to change the Thymeleaf configuration and upgrade your libraries. As it works in a small sample project this isn't a bug here. It's a bug in your project. That's why I asked for the classpath and your configuration. If you're using maven you can paste the output of `mvn dependency:tree -Dverbose` as well as your thymeleaf configuration here.

**Comment by robvanderboom** [comment]
see attachment for the mvn dependency-tree. Its big project but maybe you find something which is suspicious, i looked to it several times but do not see conflicting or old jars :-<
And what do you like to see from the thymeleaf configuration ?  It is actually exactly like in the "3 minutes migration guid",  Configuration with SpringTemplateEngine, SpringResourceTemplateResolver, and ThymeLeafViewResolver (which sets the templateengine).
[dependencytree.txt](https://github.com/mxab/thymeleaf-extras-data-attribute/files/280619/dependencytree.txt)

**Comment by dtrunk90** [comment]
Just a guess cause I missed it several times. Did you set `engine.setEnableSpringELCompiler(true);`?

**Comment by robvanderboom** [comment]
Yes i started with this because it is in the migration guide, then i thought maybe this causes the problem and removed it, and then put it back because i saw it didn't change anything (concerning the issue).

**Comment by dtrunk90** [comment]
I've made a small reproduction. There's something wrong with the thymeleaf configuration in conjunction with the messagesource. https://github.com/dtrunk90/spring-boot-thymeleaf3

Feel free to fork and try to fix the configuration. I'll do my best as well as soon I get some free time.

**Comment by mxab** [comment]
interesting, thanks for taking care of it

**Comment by dtrunk90** [comment]
Just FYI: https://github.com/thymeleaf/thymeleaf/issues/504

**Pull request merged**
